nelmio_api_doc:
    documentation:
        info:
            title: RG App API
            description: Audioguide application!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                type: http
                scheme: bearer
                bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under /api except /api/doc
